### ISSUE TITLE
regression from #126 causing stylo bindgen error "entered unreachable code: Should have been resolved after parsing!', src/ir/ty.rs:321"

### ISSUE THREAD

**Issue by heycam** [servo/rust-bindgen#160]

**Comment by heycam** [comment]
Regenerating bindings for stylo with the latest rust-bindgen results in this error during the bindings.rs generation:

```
thread 'main' panicked at 'internal error: entered unreachable code: Should have been resolved after parsing!', src/ir/ty.rs:321
```

Bisecting tells me that #126 introduced this problem.  This happens with both the current incubator/stylo Gecko sources and with a merged in mozilla-central.

cc @upsuper @emilio

**Comment by upsuper** [comment]
What's the stack with `RUST_BACKTRACE=1`?

**Comment by heycam** [comment]
This is the stack with current master (f7b5fae):

```
thread 'main' panicked at 'internal error: entered unreachable code: Should have been resolved after parsing!', src/lib.rs:57
stack backtrace:
   1:     0x55c56744b5f9 - std::sys::backtrace::tracing::imp::write::ha82a00c9c3ed2e32
   2:     0x55c567450cac - std::panicking::default_hook::_{{closure}}::h9271dcb85fc14bd9
   3:     0x55c56744ff59 - std::panicking::default_hook::h198ff0ef51316690
   4:     0x55c5674505e8 - std::panicking::rust_panic_with_hook::h079071a58cfb7bba
   5:     0x55c567450442 - std::panicking::begin_panic::h179d72dd51f16d21
   6:     0x55c5674503b0 - std::panicking::begin_panic_fmt::h04c43fa338166cb9
   7:     0x55c566e0fb49 - bindgen::ir::ty::Type::canonical_type::h2ddc12c67a483970
                        at /z/stylo/hg-incubator/servo/components/style/binding_tools/rust-bindgen/src/ir/ty.rs:8
   8:     0x55c566e0fae6 - bindgen::ir::ty::Type::canonical_type::h2ddc12c67a483970
                        at /z/stylo/hg-incubator/servo/components/style/binding_tools/rust-bindgen/src/ir/ty.rs:338
   9:     0x55c566e0fae6 - bindgen::ir::ty::Type::canonical_type::h2ddc12c67a483970
                        at /z/stylo/hg-incubator/servo/components/style/binding_tools/rust-bindgen/src/ir/ty.rs:338
  10:     0x55c566e0ee0d - bindgen::ir::ty::Type::is_integer::hb46eb1e70638e342
                        at /z/stylo/hg-incubator/servo/components/style/binding_tools/rust-bindgen/src/ir/ty.rs:128
  11:     0x55c566e48e25 - _<bindgen..ir..var..Var as bindgen..parse..ClangSubItemParser>::parse::_{{closure}}::h4dad925de4b3f7a2
                        at /z/stylo/hg-incubator/servo/components/style/binding_tools/rust-bindgen/src/ir/var.rs:123
  12:     0x55c566d1cad5 - _<core..option..Option<T>>::map_or::hbabbdc5c7a99bf33
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/obj/../src/libcore/option.rs:407
  13:     0x55c566e15475 - _<bindgen..ir..var..Var as bindgen..parse..ClangSubItemParser>::parse::h65b11a265e8f232a
                        at /z/stylo/hg-incubator/servo/components/style/binding_tools/rust-bindgen/src/ir/var.rs:122
  14:     0x55c566e0939b - _<bindgen..ir..item..Item as bindgen..parse..ClangItemParser>::parse::h58ce20b496a99d0a
                        at /z/stylo/hg-incubator/servo/components/style/binding_tools/rust-bindgen/src/ir/item.rs:660
  15:     0x55c566e4d3b4 - bindgen::ir::comp::CompInfo::from_ty::_{{closure}}::h69e98e5e3652cc2f
                        at /z/stylo/hg-incubator/servo/components/style/binding_tools/rust-bindgen/src/ir/comp.rs:701
  16:     0x55c566df1fab - bindgen::clang::visit_children::hbe9d46ca2b57bcf5
                        at /z/stylo/hg-incubator/servo/components/style/binding_tools/rust-bindgen/src/clang.rs:496
  17:     0x7f7032183e5c - <unknown>
  18:     0x7f7032187798 - <unknown>
  19:     0x7f703218397a - <unknown>
  20:     0x7f703218c4c3 - clang_visitChildren
  21:     0x55c566def8e4 - bindgen::clang::Cursor::visit::h0b11437b58a3aec3
                        at /z/stylo/hg-incubator/servo/components/style/binding_tools/rust-bindgen/src/clang.rs:305
  22:     0x55c566dfa012 - bindgen::ir::comp::CompInfo::from_ty::hd07d2f702e661139
                        at /z/stylo/hg-incubator/servo/components/style/binding_tools/rust-bindgen/src/ir/comp.rs:518
  23:     0x55c566e115bb - bindgen::ir::ty::Type::from_clang_ty::hca414d2ee8b40bbd
                        at /z/stylo/hg-incubator/servo/components/style/binding_tools/rust-bindgen/src/ir/ty.rs:663
  24:     0x55c566e0bead - _<bindgen..ir..item..Item as bindgen..parse..ClangItemParser>::from_ty_with_id::h79b0d64435ca8aea
                        at /z/stylo/hg-incubator/servo/components/style/binding_tools/rust-bindgen/src/ir/item.rs:809
  25:     0x55c566e0b469 - _<bindgen..ir..item..Item as bindgen..parse..ClangItemParser>::from_ty::ha87e800a30140af4
                        at /z/stylo/hg-incubator/servo/components/style/binding_tools/rust-bindgen/src/ir/item.rs:743
  26:     0x55c566e099bb - _<bindgen..ir..item..Item as bindgen..parse..ClangItemParser>::parse::h58ce20b496a99d0a
                        at /z/stylo/hg-incubator/servo/components/style/binding_tools/rust-bindgen/src/ir/item.rs:671
  27:     0x55c566e47910 - bindgen::parse_one::h12506215d8ab9938
                        at /z/stylo/hg-incubator/servo/components/style/binding_tools/rust-bindgen/src/lib.rs:398
  28:     0x55c566e4dabb - _<bindgen..ir..module..Module as bindgen..parse..ClangSubItemParser>::parse::_{{closure}}::_{{closure}}::hb18c04ab05a3c6e6
                        at /z/stylo/hg-incubator/servo/components/style/binding_tools/rust-bindgen/src/ir/module.rs:50
  29:     0x55c566df1fab - bindgen::clang::visit_children::hbe9d46ca2b57bcf5
                        at /z/stylo/hg-incubator/servo/components/style/binding_tools/rust-bindgen/src/clang.rs:496
  30:     0x7f7032183e5c - <unknown>
  31:     0x7f7032187798 - <unknown>
  32:     0x7f703218397a - <unknown>
  33:     0x7f703218c4c3 - clang_visitChildren
  34:     0x55c566defd2c - bindgen::clang::Cursor::visit::h1f96d9b896dc6840
                        at /z/stylo/hg-incubator/servo/components/style/binding_tools/rust-bindgen/src/clang.rs:305
  35:     0x55c566e4f89b - _<bindgen..ir..module..Module as bindgen..parse..ClangSubItemParser>::parse::_{{closure}}::h2dd25f66163a62b9
                        at /z/stylo/hg-incubator/servo/components/style/binding_tools/rust-bindgen/src/ir/module.rs:50
  36:     0x55c566e0168a - bindgen::ir::context::BindgenContext::with_module::ha9e8536323242cac
                        at /z/stylo/hg-incubator/servo/components/style/binding_tools/rust-bindgen/src/ir/context.rs:764
  37:     0x55c566e0e57f - _<bindgen..ir..module..Module as bindgen..parse..ClangSubItemParser>::parse::ha95f84387bed53b1
                        at /z/stylo/hg-incubator/servo/components/style/binding_tools/rust-bindgen/src/ir/module.rs:49
  38:     0x55c566e08a59 - _<bindgen..ir..item..Item as bindgen..parse..ClangItemParser>::parse::h58ce20b496a99d0a
                        at /z/stylo/hg-incubator/servo/components/style/binding_tools/rust-bindgen/src/ir/item.rs:650
  39:     0x55c566e47910 - bindgen::parse_one::h12506215d8ab9938
                        at /z/stylo/hg-incubator/servo/components/style/binding_tools/rust-bindgen/src/lib.rs:398
  40:     0x55c566e4da28 - bindgen::parse::_{{closure}}::_{{closure}}::h82862c6e08003459
                        at /z/stylo/hg-incubator/servo/components/style/binding_tools/rust-bindgen/src/lib.rs:426
  41:     0x55c566df1fab - bindgen::clang::visit_children::hbe9d46ca2b57bcf5
                        at /z/stylo/hg-incubator/servo/components/style/binding_tools/rust-bindgen/src/clang.rs:496
  42:     0x7f7032183e5c - <unknown>
  43:     0x7f7032187798 - <unknown>
  44:     0x7f7032183b69 - <unknown>
  45:     0x7f703218c4c3 - clang_visitChildren
  46:     0x55c566defade - bindgen::clang::Cursor::visit::h0c33ecafddf734a9
                        at /z/stylo/hg-incubator/servo/components/style/binding_tools/rust-bindgen/src/clang.rs:305
  47:     0x55c566e4f910 - bindgen::parse::_{{closure}}::hc42b72b341cfe64c
                        at /z/stylo/hg-incubator/servo/components/style/binding_tools/rust-bindgen/src/lib.rs:426
  48:     0x55c566e0196b - bindgen::ir::context::BindgenContext::with_module::hf47c5511ac2dead2
                        at /z/stylo/hg-incubator/servo/components/style/binding_tools/rust-bindgen/src/ir/context.rs:764
  49:     0x55c566e47d5a - bindgen::parse::h56c9e8952c0355fd
                        at /z/stylo/hg-incubator/servo/components/style/binding_tools/rust-bindgen/src/lib.rs:425
  50:     0x55c566e467d5 - bindgen::Bindings::generate::h36e00df0ad2aed13
                        at /z/stylo/hg-incubator/servo/components/style/binding_tools/rust-bindgen/src/lib.rs:321
  51:     0x55c566ce7ff0 - bindgen::main::hc18894e95b7160b0
                        at /z/stylo/hg-incubator/servo/components/style/binding_tools/rust-bindgen/src/bin/bindgen.rs:235
  52:     0x55c567458796 - __rust_maybe_catch_panic
  53:     0x55c56744f6d2 - std::rt::lang_start::h559690d68d7b71a6
  54:     0x55c566ce8943 - main
  55:     0x7f703161382f - __libc_start_main
  56:     0x55c566cba3b8 - _start
  57:                0x0 - <unknown>
```

**Comment by upsuper** [comment]
Hmmm, we probably want `canonical_type` to return a `Option` then.
