### ISSUE TITLE
Generating bindings that fail #[test]s for layout

### ISSUE THREAD

**Issue by fitzgen** [servo/rust-bindgen#211]
Input header:

```c++
#define JS_FRIEND_API(t) t

namespace js {
    class Klass {
      public:
        size_t x;
        size_t y;
    };

    JS_FRIEND_API(Klass) MemoryReportingSundriesThreshold();
}
```

Output bindings:

```rust
/* automatically generated by rust-bindgen */


#![allow(non_snake_case)]


#[repr(C)]
#[derive(Debug, Copy)]
pub struct Klass {
    pub x: ::std::os::raw::c_int,
    pub y: ::std::os::raw::c_int,
}
#[test]
fn bindgen_test_layout_Klass() {
    assert_eq!(::std::mem::size_of::<Klass>() , 1usize);
    assert_eq!(::std::mem::align_of::<Klass>() , 1usize);
}
impl Clone for Klass {
    fn clone(&self) -> Self { *self }
}
extern "C" {
    #[link_name = "_ZN2js32MemoryReportingSundriesThresholdEv"]
    pub fn MemoryReportingSundriesThreshold() -> Klass;
}
```

This fails when we run the `#[test]`s for the layout:

```
run-bindgen.py: running ['./target/debug/bindgen', '-o', 'tests/expectations/js_friend_api.rs', '--no-unstable-rust', '--raw-line', '', '--raw-line', '#![allow(non_snake_case)]', '--raw-line', '', 'tests/headers/js_friend_api.hpp']
INFO:bindgen: Clang Version: clang version 4.0.0 (http://llvm.org/git/clang ed0c7d6ff0e1859c6e883844579ba2794a848e50) (http://llvm.org/git/llvm e994d796e28fa1044bac2a894cb982486e56c3fa)
ERROR:bindgen: Using clang (4, 0), expected (3, 9)
tests/headers/js_friend_api.hpp:6:9: error: unknown type name 'size_t'
tests/headers/js_friend_api.hpp:7:9: error: unknown type name 'size_t'
DEBUG:bindgen::ir::context: BindgenContext::add_item(Item { id: ItemId(0), local_id: Cell { value: None }, next_child_local_id: Cell { value: 1 }, canonical_name_cache: RefCell { value: None }, comment: None, annotations: Annotations { opaque: false, hide: false, use_instead_of: None, disallow_copy: false, private_fields: None, accessor_kind: None }, parent_id: ItemId(0), kind: Module(Module { name: Some("root"), children_ids: [] }) }, declaration: None, loc: None
tests/headers/js_friend_api.hpp:6:9: error: unknown type name 'size_t', err: true
tests/headers/js_friend_api.hpp:7:9: error: unknown type name 'size_t', err: true
DEBUG:bindgen::ir::context: builtin_or_resolved_ty: Type(, kind: Invalid, decl: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None), canon: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None)), Some(Cursor(JS_FRIEND_API kind: macro definition, loc: tests/headers/js_friend_api.hpp:1:9, usr: Some("c:js_friend_api.hpp@8@macro@JS_FRIEND_API"))), None
DEBUG:bindgen::ir::context: Not resolved, maybe builtin?
DEBUG:bindgen::ir::context: builtin_or_resolved_ty: Type(, kind: Invalid, decl: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None), canon: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None)), Some(Cursor(JS_FRIEND_API kind: macro definition, loc: tests/headers/js_friend_api.hpp:1:9, usr: Some("c:js_friend_api.hpp@8@macro@JS_FRIEND_API"))), None
DEBUG:bindgen::ir::context: Not resolved, maybe builtin?
DEBUG:bindgen::ir::ty: from_clang_ty: ItemId(1), ty: Type(, kind: Invalid, decl: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None), canon: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None)), loc: Some(Cursor(JS_FRIEND_API kind: macro definition, loc: tests/headers/js_friend_api.hpp:1:9, usr: Some("c:js_friend_api.hpp@8@macro@JS_FRIEND_API")))
DEBUG:bindgen::ir::ty: currently_parsed_types: []
WARN:bindgen::ir::ty: invalid type Type(, kind: Invalid, decl: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None), canon: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None))
DEBUG:bindgen::ir::item: Unhandled cursor kind 501: Cursor(JS_FRIEND_API kind: macro definition, loc: tests/headers/js_friend_api.hpp:1:9, usr: Some("c:js_friend_api.hpp@8@macro@JS_FRIEND_API"))
DEBUG:bindgen::ir::context: builtin_or_resolved_ty: Type(, kind: Invalid, decl: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None), canon: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None)), Some(Cursor(JS_FRIEND_API kind: macro definition, loc: tests/headers/js_friend_api.hpp:1:9, usr: Some("c:js_friend_api.hpp@8@macro@JS_FRIEND_API"))), None
DEBUG:bindgen::ir::context: Not resolved, maybe builtin?
DEBUG:bindgen::ir::context: builtin_or_resolved_ty: Type(, kind: Invalid, decl: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None), canon: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None)), Some(Cursor(JS_FRIEND_API kind: macro definition, loc: tests/headers/js_friend_api.hpp:1:9, usr: Some("c:js_friend_api.hpp@8@macro@JS_FRIEND_API"))), None
DEBUG:bindgen::ir::context: Not resolved, maybe builtin?
DEBUG:bindgen::ir::ty: from_clang_ty: ItemId(2), ty: Type(, kind: Invalid, decl: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None), canon: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None)), loc: Some(Cursor(JS_FRIEND_API kind: macro definition, loc: tests/headers/js_friend_api.hpp:1:9, usr: Some("c:js_friend_api.hpp@8@macro@JS_FRIEND_API")))
DEBUG:bindgen::ir::ty: currently_parsed_types: []
WARN:bindgen::ir::ty: invalid type Type(, kind: Invalid, decl: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None), canon: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None))
ERROR:bindgen::ir::item: Unhandled cursor kind 502: Cursor(JS_FRIEND_API kind: macro expansion, loc: tests/headers/js_friend_api.hpp:10:5, usr: None)
DEBUG:bindgen::ir::context: BindgenContext::add_item(Item { id: ItemId(3), local_id: Cell { value: None }, next_child_local_id: Cell { value: 1 }, canonical_name_cache: RefCell { value: None }, comment: None, annotations: Annotations { opaque: false, hide: false, use_instead_of: None, disallow_copy: false, private_fields: None, accessor_kind: None }, parent_id: ItemId(0), kind: Module(Module { name: Some("js"), children_ids: [] }) }, declaration: None, loc: None
DEBUG:bindgen::ir::context: builtin_or_resolved_ty: Type(js::Klass, kind: Record, decl: Cursor(Klass kind: ClassDecl, loc: tests/headers/js_friend_api.hpp:4:11, usr: Some("c:@N@js@S@Klass")), canon: Cursor(Klass kind: ClassDecl, loc: tests/headers/js_friend_api.hpp:4:11, usr: Some("c:@N@js@S@Klass"))), Some(Cursor(Klass kind: ClassDecl, loc: tests/headers/js_friend_api.hpp:4:11, usr: Some("c:@N@js@S@Klass"))), Some(ItemId(3))
DEBUG:bindgen::ir::context: Not resolved, maybe builtin?
DEBUG:bindgen::ir::context: builtin_or_resolved_ty: Type(js::Klass, kind: Record, decl: Cursor(Klass kind: ClassDecl, loc: tests/headers/js_friend_api.hpp:4:11, usr: Some("c:@N@js@S@Klass")), canon: Cursor(Klass kind: ClassDecl, loc: tests/headers/js_friend_api.hpp:4:11, usr: Some("c:@N@js@S@Klass"))), Some(Cursor(Klass kind: ClassDecl, loc: tests/headers/js_friend_api.hpp:4:11, usr: Some("c:@N@js@S@Klass"))), Some(ItemId(3))
DEBUG:bindgen::ir::context: Not resolved, maybe builtin?
DEBUG:bindgen::ir::ty: from_clang_ty: ItemId(4), ty: Type(js::Klass, kind: Record, decl: Cursor(Klass kind: ClassDecl, loc: tests/headers/js_friend_api.hpp:4:11, usr: Some("c:@N@js@S@Klass")), canon: Cursor(Klass kind: ClassDecl, loc: tests/headers/js_friend_api.hpp:4:11, usr: Some("c:@N@js@S@Klass"))), loc: Some(Cursor(Klass kind: ClassDecl, loc: tests/headers/js_friend_api.hpp:4:11, usr: Some("c:@N@js@S@Klass")))
DEBUG:bindgen::ir::ty: currently_parsed_types: [(Cursor(Klass kind: ClassDecl, loc: tests/headers/js_friend_api.hpp:4:11, usr: Some("c:@N@js@S@Klass")), ItemId(4))]
DEBUG:bindgen::ir::comp: CompInfo::from_ty(Struct, Cursor(Klass kind: ClassDecl, loc: tests/headers/js_friend_api.hpp:4:11, usr: Some("c:@N@js@S@Klass")))
DEBUG:bindgen::ir::item: from_ty_or_ref_with_id: ItemId(5) Type(int, kind: Int, decl: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None), canon: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None)), Some(Cursor(x kind: FieldDecl, loc: tests/headers/js_friend_api.hpp:6:16, usr: Some("c:@N@js@S@Klass@FI@x"))), Some(ItemId(4))
DEBUG:bindgen::ir::context: builtin_or_resolved_ty: Type(int, kind: Int, decl: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None), canon: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None)), Some(Cursor(x kind: FieldDecl, loc: tests/headers/js_friend_api.hpp:6:16, usr: Some("c:@N@js@S@Klass@FI@x"))), Some(ItemId(4))
DEBUG:bindgen::ir::context: Not resolved, maybe builtin?
DEBUG:bindgen::ir::item: ItemId(6) already resolved: Some(Cursor(x kind: FieldDecl, loc: tests/headers/js_friend_api.hpp:6:16, usr: Some("c:@N@js@S@Klass@FI@x")))
DEBUG:bindgen::ir::item: from_ty_or_ref_with_id: ItemId(7) Type(int, kind: Int, decl: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None), canon: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None)), Some(Cursor(y kind: FieldDecl, loc: tests/headers/js_friend_api.hpp:7:16, usr: Some("c:@N@js@S@Klass@FI@y"))), Some(ItemId(4))
DEBUG:bindgen::ir::context: builtin_or_resolved_ty: Type(int, kind: Int, decl: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None), canon: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None)), Some(Cursor(y kind: FieldDecl, loc: tests/headers/js_friend_api.hpp:7:16, usr: Some("c:@N@js@S@Klass@FI@y"))), Some(ItemId(4))
DEBUG:bindgen::ir::context: Not resolved, maybe builtin?
DEBUG:bindgen::ir::item: ItemId(8) already resolved: Some(Cursor(y kind: FieldDecl, loc: tests/headers/js_friend_api.hpp:7:16, usr: Some("c:@N@js@S@Klass@FI@y")))
DEBUG:bindgen::ir::context: BindgenContext::add_item(Item { id: ItemId(4), local_id: Cell { value: None }, next_child_local_id: Cell { value: 1 }, canonical_name_cache: RefCell { value: None }, comment: None, annotations: Annotations { opaque: false, hide: false, use_instead_of: None, disallow_copy: false, private_fields: None, accessor_kind: None }, parent_id: ItemId(3), kind: Type(Type { name: Some("Klass"), layout: Some(Layout { size: 1, align: 1, packed: false }), kind: Comp(CompInfo { kind: Struct, fields: [Field { name: Some("x"), ty: ItemId(6), comment: None, annotations: Annotations { opaque: false, hide: false, use_instead_of: None, disallow_copy: false, private_fields: None, accessor_kind: None }, bitfield: None, mutable: false }, Field { name: Some("y"), ty: ItemId(8), comment: None, annotations: Annotations { opaque: false, hide: false, use_instead_of: None, disallow_copy: false, private_fields: None, accessor_kind: None }, bitfield: None, mutable: false }], template_args: [], methods: [], base_members: [], ref_template: None, inner_types: [], inner_vars: [], has_vtable: false, has_destructor: false, has_nonempty_base: false, has_non_type_template_params: false, packed: false, is_anonymous: false, found_unknown_attr: false, detect_derive_debug_cycle: Cell { value: false }, detect_has_destructor_cycle: Cell { value: false } }), is_const: false }) }, declaration: Some(Cursor(Klass kind: ClassDecl, loc: tests/headers/js_friend_api.hpp:4:11, usr: Some("c:@N@js@S@Klass"))), loc: Some(Cursor(Klass kind: ClassDecl, loc: tests/headers/js_friend_api.hpp:4:11, usr: Some("c:@N@js@S@Klass")))
DEBUG:bindgen::ir::function: Function::parse(Cursor(MemoryReportingSundriesThreshold kind: FunctionDecl, loc: tests/headers/js_friend_api.hpp:10:26, usr: Some("c:@N@js@F@MemoryReportingSundriesThreshold#")), Type(js::Klass (), kind: FunctionProto, decl: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None), canon: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None)))
DEBUG:bindgen::ir::context: builtin_or_resolved_ty: Type(js::Klass (), kind: FunctionProto, decl: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None), canon: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None)), Some(Cursor(MemoryReportingSundriesThreshold kind: FunctionDecl, loc: tests/headers/js_friend_api.hpp:10:26, usr: Some("c:@N@js@F@MemoryReportingSundriesThreshold#"))), None
DEBUG:bindgen::ir::context: Not resolved, maybe builtin?
DEBUG:bindgen::ir::context: builtin_or_resolved_ty: Type(js::Klass (), kind: FunctionProto, decl: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None), canon: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None)), Some(Cursor(MemoryReportingSundriesThreshold kind: FunctionDecl, loc: tests/headers/js_friend_api.hpp:10:26, usr: Some("c:@N@js@F@MemoryReportingSundriesThreshold#"))), None
DEBUG:bindgen::ir::context: Not resolved, maybe builtin?
DEBUG:bindgen::ir::ty: from_clang_ty: ItemId(9), ty: Type(js::Klass (), kind: FunctionProto, decl: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None), canon: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None)), loc: Some(Cursor(MemoryReportingSundriesThreshold kind: FunctionDecl, loc: tests/headers/js_friend_api.hpp:10:26, usr: Some("c:@N@js@F@MemoryReportingSundriesThreshold#")))
DEBUG:bindgen::ir::ty: currently_parsed_types: []
DEBUG:bindgen::ir::function: FunctionSig::from_ty Type(js::Klass (), kind: FunctionProto, decl: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None), canon: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None)) Cursor(MemoryReportingSundriesThreshold kind: FunctionDecl, loc: tests/headers/js_friend_api.hpp:10:26, usr: Some("c:@N@js@F@MemoryReportingSundriesThreshold#"))
DEBUG:bindgen::ir::context: builtin_or_resolved_ty: Type(js::Klass, kind: Record, decl: Cursor(Klass kind: ClassDecl, loc: tests/headers/js_friend_api.hpp:4:11, usr: Some("c:@N@js@S@Klass")), canon: Cursor(Klass kind: ClassDecl, loc: tests/headers/js_friend_api.hpp:4:11, usr: Some("c:@N@js@S@Klass"))), None, None
DEBUG:bindgen::ir::context: Already resolved ty ItemId(4), Cursor(Klass kind: ClassDecl, loc: tests/headers/js_friend_api.hpp:4:11, usr: Some("c:@N@js@S@Klass")), Type(js::Klass, kind: Record, decl: Cursor(Klass kind: ClassDecl, loc: tests/headers/js_friend_api.hpp:4:11, usr: Some("c:@N@js@S@Klass")), canon: Cursor(Klass kind: ClassDecl, loc: tests/headers/js_friend_api.hpp:4:11, usr: Some("c:@N@js@S@Klass"))) None
DEBUG:bindgen::ir::context: BindgenContext::add_item(Item { id: ItemId(9), local_id: Cell { value: None }, next_child_local_id: Cell { value: 1 }, canonical_name_cache: RefCell { value: None }, comment: None, annotations: Annotations { opaque: false, hide: false, use_instead_of: None, disallow_copy: false, private_fields: None, accessor_kind: None }, parent_id: ItemId(3), kind: Type(Type { name: None, layout: Some(Layout { size: 1, align: 4, packed: false }), kind: Function(FunctionSig { return_type: ItemId(10), argument_types: [], is_variadic: false, abi: C }), is_const: false }) }, declaration: Some(Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None)), loc: Some(Cursor(MemoryReportingSundriesThreshold kind: FunctionDecl, loc: tests/headers/js_friend_api.hpp:10:26, usr: Some("c:@N@js@F@MemoryReportingSundriesThreshold#")))
DEBUG:bindgen::ir::context: Invalid declaration Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None) found for type Type { name: None, layout: Some(Layout { size: 1, align: 4, packed: false }), kind: Function(FunctionSig { return_type: ItemId(10), argument_types: [], is_variadic: false, abi: C }), is_const: false }
DEBUG:bindgen::ir::context: BindgenContext::add_item(Item { id: ItemId(11), local_id: Cell { value: None }, next_child_local_id: Cell { value: 1 }, canonical_name_cache: RefCell { value: None }, comment: None, annotations: Annotations { opaque: false, hide: false, use_instead_of: None, disallow_copy: false, private_fields: None, accessor_kind: None }, parent_id: ItemId(3), kind: Function(Function { name: "MemoryReportingSundriesThreshold", mangled_name: Some("_ZN2js32MemoryReportingSundriesThresholdEv"), signature: ItemId(9), comment: None }) }, declaration: Some(Cursor(MemoryReportingSundriesThreshold kind: FunctionDecl, loc: tests/headers/js_friend_api.hpp:10:26, usr: Some("c:@N@js@F@MemoryReportingSundriesThreshold#"))), loc: Some(Cursor(MemoryReportingSundriesThreshold kind: FunctionDecl, loc: tests/headers/js_friend_api.hpp:10:26, usr: Some("c:@N@js@F@MemoryReportingSundriesThreshold#")))
DEBUG:bindgen::ir::context: No replacements to process
DEBUG:bindgen::codegen: codegen: BindgenOptions { hidden_types: {}, opaque_types: {}, whitelisted_types: RegexSet { items: [] }, whitelisted_functions: RegexSet { items: [] }, whitelisted_vars: RegexSet { items: [] }, builtins: false, links: [], emit_ast: false, ignore_functions: false, ignore_methods: false, enable_cxx_namespaces: false, derive_debug: true, unstable_rust: false, namespaced_constants: true, msvc_mangling: false, raw_lines: ["", "#![allow(non_snake_case)]", ""], clang_args: ["-isystem", "/usr/bin/../lib/gcc/x86_64-redhat-linux/6.1.1/../../../../include/c++/6.1.1", "-isystem", "/usr/bin/../lib/gcc/x86_64-redhat-linux/6.1.1/../../../../include/c++/6.1.1/x86_64-redhat-linux", "-isystem", "/usr/bin/../lib/gcc/x86_64-redhat-linux/6.1.1/../../../../include/c++/6.1.1/backward", "-isystem", "/usr/local/include", "-isystem", "/usr/bin/../lib64/clang/3.8.0/include", "-isystem", "/usr/include", "tests/headers/js_friend_api.hpp"], input_header: Some("tests/headers/js_friend_api.hpp"), dummy_uses: None }
DEBUG:bindgen::ir::ty: Ignoring: Int(Int)
DEBUG:bindgen::ir::ty: Ignoring: Int(Int)
DEBUG:bindgen::ir::ty: Ignoring: Int(Int)
DEBUG:bindgen::ir::ty: Ignoring: Int(Int)
DEBUG:bindgen::ir::ty: Ignoring: Int(Int)
DEBUG:bindgen::ir::ty: Ignoring: Int(Int)
DEBUG:bindgen::ir::ty: Ignoring: Int(Int)
DEBUG:bindgen::ir::ty: Ignoring: Int(Int)
run-bindgen.py: running ['rustc', '--test', 'tests/expectations/js_friend_api.rs', '-o', '/tmp/tmpcXl5QH']
run-bindgen.py: running ['/tmp/tmpcXl5QH']

running 1 test
test bindgen_test_layout_Klass ... FAILED

failures:

---- bindgen_test_layout_Klass stdout ----
	thread 'bindgen_test_layout_Klass' panicked at 'assertion failed: `(left == right)` (left: `8`, right: `1`)', tests/expectations/js_friend_api.rs:15
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    bindgen_test_layout_Klass

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured

Traceback (most recent call last):
  File "./tests/tools/run-bindgen.py", line 185, in <module>
    main()
  File "./tests/tools/run-bindgen.py", line 180, in main
    test_generated_bindings(args.rust_bindings)
  File "./tests/tools/run-bindgen.py", line 141, in test_generated_bindings
    run_cmd([name])
  File "./tests/tools/run-bindgen.py", line 122, in run_cmd
    subprocess.check_call(command, **kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/tmp/tmpcXl5QH']' returned non-zero exit status 101
```

**Comment by fitzgen** [comment]
@emilio thoughts?

It seems like we shouldn't be using `c_int` for `size_t`, should we? Additionally, our expected layout seems pretty wrong...

**Comment by emilio** [comment]
That's more than expected, given `size_t` isn't defined for clang, so it's normal the layout is messed up.

It'll work fine if you include `<cstddef>` or the relevant header.

**Comment by emilio** [comment]
Yup, I can't reproduce this with the correct includes.
