### ISSUE TITLE
thread 'main' panicked at 'internal error: entered unreachable code: Not a named type: ResolvedTypeRef(ItemId(48235))', src/ir/ty.rs:322

### ISSUE THREAD

**Issue by fitzgen** [servo/rust-bindgen#358]
Just got this on the spidermonkey bindings. Will minimize with `creduce`.

```
thread 'main' panicked at 'internal error: entered unreachable code: Not a named type: ResolvedTypeRef(ItemId(48235))', src/ir/ty.rs:322
stack backtrace:
   1:     0x55fa3841400a - std::sys::imp::backtrace::tracing::imp::write::hbea47d9dd19b523c
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x55fa3841896f - std::panicking::default_hook::{{closure}}::h6875a2976258b020
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:247
   3:     0x55fa3841856e - std::panicking::default_hook::h88ffbc5922643264
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:263
   4:     0x55fa38418db7 - std::panicking::rust_panic_with_hook::hc790e47d4ecc86cd
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:451
   5:     0x55fa38418c44 - std::panicking::begin_panic::hc066339e2fdc17d1
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:413
   6:     0x55fa38418b69 - std::panicking::begin_panic_fmt::h5912b2d2df332044
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:397
   7:     0x55fa381b059d - libbindgen::ir::ty::Type::signature_contains_named_type::h5c3e35ec67234e8c
   8:     0x55fa381d464d - <libbindgen::ir::comp::CompInfo as libbindgen::codegen::CodeGenerator>::codegen::h9e1f0ffff8cef771
   9:     0x55fa381c68f1 - <libbindgen::ir::ty::Type as libbindgen::codegen::CodeGenerator>::codegen::hdf8b044d295a3662
  10:     0x55fa381bd8e7 - <libbindgen::ir::item::Item as libbindgen::codegen::CodeGenerator>::codegen::h8e4936a9fbad2b52
  11:     0x55fa381bead3 - <libbindgen::ir::module::Module as libbindgen::codegen::CodeGenerator>::codegen::{{closure}}::h356f8e678bf1a376
  12:     0x55fa381c26fd - <libbindgen::ir::module::Module as libbindgen::codegen::CodeGenerator>::codegen::{{closure}}::h24c75a935de1f120
  13:     0x55fa381bdbdc - <libbindgen::ir::module::Module as libbindgen::codegen::CodeGenerator>::codegen::h311b6a0b33b41b67
  14:     0x55fa381bd900 - <libbindgen::ir::item::Item as libbindgen::codegen::CodeGenerator>::codegen::h8e4936a9fbad2b52
  15:     0x55fa381bead3 - <libbindgen::ir::module::Module as libbindgen::codegen::CodeGenerator>::codegen::{{closure}}::h356f8e678bf1a376
  16:     0x55fa381c26fd - <libbindgen::ir::module::Module as libbindgen::codegen::CodeGenerator>::codegen::{{closure}}::h24c75a935de1f120
  17:     0x55fa381bdbdc - <libbindgen::ir::module::Module as libbindgen::codegen::CodeGenerator>::codegen::h311b6a0b33b41b67
  18:     0x55fa381bd900 - <libbindgen::ir::item::Item as libbindgen::codegen::CodeGenerator>::codegen::h8e4936a9fbad2b52
  19:     0x55fa381b649b - libbindgen::Bindings::generate::h27d0348e575e4b2e
  20:     0x55fa381b5016 - libbindgen::Builder::generate::hfe788fbf8ffd061c
  21:     0x55fa3816624e - bindgen::main::h8863cb0a577a166e
  22:     0x55fa3842186a - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libpanic_unwind/lib.rs:97
  23:     0x55fa384195fa - std::rt::lang_start::h5d71a3afaaa4b2ff
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:332
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panic.rs:351
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/rt.rs:57
  24:     0x7f467a250730 - __libc_start_main
  25:     0x55fa38146148 - _start
  26:                0x0 - <unknown>
```

**Comment by emilio** [comment]
@fitzgen does this reproduce with #360?

**Comment by fitzgen** [comment]
Reduced test case:

```C++
namespace JS {
template <typename> class PersistentRooted;
}
template <typename> class a { a *b; };
namespace JS {
template <typename c> class PersistentRooted : a<PersistentRooted<c>> {};
}
```

@emilio I'll give it a try when I get into the office.

**Comment by emilio** [comment]
It's the same issue, I'll include the test case.

(That C++ is nasty btw :P)

**Comment by fitzgen** [comment]
> (That C++ is nasty btw :P)

`creduce` never fails to deliver ;)
