### ISSUE TITLE
Urho3D build failing.

### ISSUE THREAD

**Issue by kkimdev** [servo/rust-bindgen#702]
### Input C/C++ Header
Selected Urho3D headers https://github.com/urho3d/Urho3D

### Bindgen Invocation

```Bash
$ bindgen urho3d_all.h -o generated.rs --whitelist-type="Urho3D::.*" -- -I./include/ -I./include/Urho3D/ThirdParty/ -x c++ -std=c++1z
```

### Actual Results

```
/usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/include/xmmintrin.h:1353:10: error: use of undeclared identifier '__builtin_ia32_cvttss2si'
/usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/include/xmmintrin.h:1389:10: error: use of undeclared identifier '__builtin_ia32_cvttss2si64'
/usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/include/xmmintrin.h:1732:18: error: use of undeclared identifier '__builtin_ia32_undef128'
/usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/include/xmmintrin.h:2083:3: error: use of undeclared identifier '__builtin_nontemporal_store'
/usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/include/xmmintrin.h:2889:44: error: token is not a valid binary operator in a preprocessor subexpression
/usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/include/emmintrin.h:420:18: error: use of undeclared identifier '__builtin_ia32_cvtsd2ss'
/usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/include/emmintrin.h:446:10: error: use of undeclared identifier '__builtin_ia32_cvttsd2si'
/usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/include/emmintrin.h:550:19: error: use of undeclared identifier '__builtin_ia32_undef128'
/usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/include/emmintrin.h:1709:10: error: use of undeclared identifier '__builtin_ia32_cvttsd2si64'
/usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/include/emmintrin.h:1899:19: error: use of undeclared identifier '__builtin_ia32_undef128'
/usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/include/emmintrin.h:2220:3: error: use of undeclared identifier '__builtin_nontemporal_store'
/usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/include/emmintrin.h:2226:3: error: use of undeclared identifier '__builtin_nontemporal_store'
/usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/include/emmintrin.h:2450:3: error: use of undeclared identifier '__builtin_ia32_pause'
/usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/include/xmmintrin.h:1353:10: error: use of undeclared identifier '__builtin_ia32_cvttss2si', err: true
/usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/include/xmmintrin.h:1389:10: error: use of undeclared identifier '__builtin_ia32_cvttss2si64', err: true
/usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/include/xmmintrin.h:1732:18: error: use of undeclared identifier '__builtin_ia32_undef128', err: true
/usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/include/xmmintrin.h:2083:3: error: use of undeclared identifier '__builtin_nontemporal_store', err: true
/usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/include/xmmintrin.h:2889:44: error: token is not a valid binary operator in a preprocessor subexpression, err: true
/usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/include/emmintrin.h:420:18: error: use of undeclared identifier '__builtin_ia32_cvtsd2ss', err: true
/usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/include/emmintrin.h:446:10: error: use of undeclared identifier '__builtin_ia32_cvttsd2si', err: true
/usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/include/emmintrin.h:550:19: error: use of undeclared identifier '__builtin_ia32_undef128', err: true
/usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/include/emmintrin.h:1709:10: error: use of undeclared identifier '__builtin_ia32_cvttsd2si64', err: true
/usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/include/emmintrin.h:1899:19: error: use of undeclared identifier '__builtin_ia32_undef128', err: true
/usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/include/emmintrin.h:2220:3: error: use of undeclared identifier '__builtin_nontemporal_store', err: true
/usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/include/emmintrin.h:2226:3: error: use of undeclared identifier '__builtin_nontemporal_store', err: true
/usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/include/emmintrin.h:2450:3: error: use of undeclared identifier '__builtin_ia32_pause', err: true
thread 'main' panicked at 'Unable to generate bindings: ()', /checkout/src/libcore/result.rs:859
note: Run with `RUST_BACKTRACE=1` for a backtrace.

```
### `RUST_LOG=bindgen` Output

<details>

```
INFO:bindgen: Clang Version: Ubuntu clang version 3.6.2-3ubuntu2 (tags/RELEASE_362/final) (based on LLVM 3.6.2)
WARN:bindgen: Couldn't parse libclang version
/usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/include/xmmintrin.h:1353:10: error: use of undeclared identifier '__builtin_ia32_cvttss2si'
/usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/include/xmmintrin.h:1389:10: error: use of undeclared identifier '__builtin_ia32_cvttss2si64'
/usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/include/xmmintrin.h:1732:18: error: use of undeclared identifier '__builtin_ia32_undef128'
/usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/include/xmmintrin.h:2083:3: error: use of undeclared identifier '__builtin_nontemporal_store'
/usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/include/xmmintrin.h:2889:44: error: token is not a valid binary operator in a preprocessor subexpression
/usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/include/emmintrin.h:420:18: error: use of undeclared identifier '__builtin_ia32_cvtsd2ss'
/usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/include/emmintrin.h:446:10: error: use of undeclared identifier '__builtin_ia32_cvttsd2si'
/usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/include/emmintrin.h:550:19: error: use of undeclared identifier '__builtin_ia32_undef128'
/usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/include/emmintrin.h:1709:10: error: use of undeclared identifier '__builtin_ia32_cvttsd2si64'
/usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/include/emmintrin.h:1899:19: error: use of undeclared identifier '__builtin_ia32_undef128'
/usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/include/emmintrin.h:2220:3: error: use of undeclared identifier '__builtin_nontemporal_store'
/usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/include/emmintrin.h:2226:3: error: use of undeclared identifier '__builtin_nontemporal_store'
/usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/include/emmintrin.h:2450:3: error: use of undeclared identifier '__builtin_ia32_pause'
DEBUG:bindgen::ir::context: BindgenContext::add_item(Item { id: ItemId(0), local_id: Cell { value: None }, next_child_local_id: Cell { value: 1 }, canonical_name_cache: RefCell { value: None }, comment: None, annotations: Annotations { opaque: false, hide: false, use_instead_of: None, disallow_copy: false, private_fields: None, accessor_kind: None, constify_enum_variant: false }, parent_id: ItemId(0), kind: Module(Module { name: Some("root"), kind: Normal, children_ids: [] }), detect_derive_debug_cycle: Cell { value: false }, detect_derive_copy_cycle: Cell { value: false } }, declaration: None, loc: None
/usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/include/xmmintrin.h:1353:10: error: use of undeclared identifier '__builtin_ia32_cvttss2si', err: true
/usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/include/xmmintrin.h:1389:10: error: use of undeclared identifier '__builtin_ia32_cvttss2si64', err: true
/usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/include/xmmintrin.h:1732:18: error: use of undeclared identifier '__builtin_ia32_undef128', err: true
/usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/include/xmmintrin.h:2083:3: error: use of undeclared identifier '__builtin_nontemporal_store', err: true
/usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/include/xmmintrin.h:2889:44: error: token is not a valid binary operator in a preprocessor subexpression, err: true
/usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/include/emmintrin.h:420:18: error: use of undeclared identifier '__builtin_ia32_cvtsd2ss', err: true
/usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/include/emmintrin.h:446:10: error: use of undeclared identifier '__builtin_ia32_cvttsd2si', err: true
/usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/include/emmintrin.h:550:19: error: use of undeclared identifier '__builtin_ia32_undef128', err: true
/usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/include/emmintrin.h:1709:10: error: use of undeclared identifier '__builtin_ia32_cvttsd2si64', err: true
/usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/include/emmintrin.h:1899:19: error: use of undeclared identifier '__builtin_ia32_undef128', err: true
/usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/include/emmintrin.h:2220:3: error: use of undeclared identifier '__builtin_nontemporal_store', err: true
/usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/include/emmintrin.h:2226:3: error: use of undeclared identifier '__builtin_nontemporal_store', err: true
/usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/include/emmintrin.h:2450:3: error: use of undeclared identifier '__builtin_ia32_pause', err: true
thread 'main' panicked at 'Unable to generate bindings: ()', /checkout/src/libcore/result.rs:859
note: Run with `RUST_BACKTRACE=1` for a backtrace.

```

</details>

I don't think this is rust-bindgen, but my configuration is messed up. RUST_LOG=bindgen outputs `INFO:bindgen: Clang Version: Ubuntu clang version 3.6.2-3ubuntu2 (tags/RELEASE_362/final) (based on LLVM 3.6.2)`  while it's reading 3.9's headers.. How can I fix this?

**Comment by kkimdev** [comment]
removed libclang 3.6.....

**Comment by emilio** [comment]
cc @wafflespeanut, which had a similar error recently. I wonder if we can detect this somehow...
